[general]
import = [
    "~/.config/alacritty/keybinds.toml",
    "~/.config/alacritty/themes/hyper.toml",
]

live_config_reload = true


[terminal]
osc52 = "CopyPaste"

[font]
size = 13

[window]
dynamic_title = true
blur = true
opacity = 0.6
dimensions = { columns = 90, lines = 30 }
padding = { x = 16, y = 8 }
startup_mode = "Windowed"
decorations = "transparent"
# dynamic_padding = true

[cursor]
style = { blinking = "Always", shape = "Beam" }

[scrolling]
history = 100000

